#!/usr/bin/env node
"use strict";
// MIT License header
// This script scaffolds a new tenant (company) for AppFactory-Final.
// Usage: node packages/create-app/src/create-company.js --name "Acme Co" --color "#4F46E5" --stripe-key sk_test_... --domain acme.app

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

function parseArgs() {
  const args = process.argv.slice(2)
  const toObj = (pairs) => {
    const obj = {}
    for (let i = 0; i < pairs.length; i++) {
      const [k, v] = pairs[i].split('=')
      obj[k.replace(/^--/, '')] = v ?? true
    }
    return obj
  }
  // basic parsing for --name --color --stripe-key --domain
  const map = {}
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      const key = args[i].replace(/^--/, '')
      const val = (i + 1 < args.length && !args[i + 1].startsWith('--')) ? args[i + 1] : true
      map[key] = val
    }
  }
  return map
}

async function main() {
  const cfg = parseArgs()
  const name = String(cfg.name || 'NewTenant')
  const color = String(cfg.color || '#4F46E5')
  const domain = String(cfg.domain || (name.toLowerCase().replace(/\s+/g, '-') + '.app'))

  // Normalize tenant slug
  const slug = name.toLowerCase().trim().replace(/\s+/g, '-')

  const root = path.resolve(__dirname, '../../..')
  const tenantsDir = path.join(root, 'apps', 'web', 'tenants')
  const tenantDir = path.join(tenantsDir, slug)
  try {
    fs.mkdirSync(tenantDir, { recursive: true })
  } catch (e) {
    // ignore if exists
  }

  // DB migration stub
  const migrationPath = path.join(tenantDir, 'db-migration.sql')
  fs.writeFileSync(migrationPath, `-- Migration for tenant ${slug}\nCREATE SCHEMA IF NOT EXISTS ${slug};\n`)

  // Netlify site stub
  const netlifyPath = path.join(tenantDir, 'netlify-site.json')
  fs.writeFileSync(netlifyPath, JSON.stringify({ siteName: name + ' - Netlify', color, tenant: slug }, null, 2))

  // Tenant config update
  const tenantsConfigPath = path.join(root, 'apps', 'web', 'tenants.json')
  let tenantsConfig = {}
  try {
    if (fs.existsSync(tenantsConfigPath)) {
      tenantsConfig = JSON.parse(fs.readFileSync(tenantsConfigPath, 'utf-8'))
    }
  } catch (e) {
    tenantsConfig = {}
  }
  tenantsConfig[slug] = { name, color }
  fs.writeFileSync(tenantsConfigPath, JSON.stringify(tenantsConfig, null, 2))

  // README for the tenant folder
  const readmePath = path.join(tenantDir, 'README.md')
  fs.writeFileSync(readmePath, `# ${name}\n\nTenant scaffold generated by AppFactory-Final create-company CLI.\n`)

  // Optional git commit if repo exists
  const gitDir = path.resolve(root, '.git')
  try {
    if (fs.existsSync(gitDir)) {
      const { execSync } = await import('child_process')
      execSync(`git add -A`, { stdio: 'inherit' })
      execSync(`git commit -m "feat(tenant): add new tenant ${slug}"`, { stdio: 'inherit' })
    }
  } catch {}

  console.log(`Tenant '${name}' created at ${tenantDir}`)
  console.log(`Migration: ${migrationPath}`)
  console.log(`Netlify: ${netlifyPath}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
